2024-12-13 17:21:56,901 - contact.py - global_logger - INFO - Data of bitsh is in the future
2024-12-13 17:26:40,590 - contact.py - global_logger - INFO - Data of bitsh is in the future
2024-12-13 18:45:52,674 - conection_postgres.py - global_logger - ERROR - Session rollback, exception: When initializing mapper Mapper[ContactsTable(contact)], expression 'User' failed to locate a name ('User'). If this is a class name, consider adding this relationship() to the <class 'src.entity.contacts.contacts_model.ContactsTable'> class after both dependent classes have been defined.
2024-12-13 18:50:10,906 - conection_postgres.py - global_logger - ERROR - Session rollback, exception: When initializing mapper Mapper[ContactsTable(contact)], expression 'UsersTabler' failed to locate a name ('UsersTabler'). If this is a class name, consider adding this relationship() to the <class 'src.entity.contacts.contacts_model.ContactsTable'> class after both dependent classes have been defined.
2024-12-13 19:04:49,139 - conection_postgres.py - global_logger - ERROR - Session rollback, exception: When initializing mapper Mapper[UserTokensTeble(user_tokens)], expression 'User' failed to locate a name ('User'). If this is a class name, consider adding this relationship() to the <class 'src.entity.models.UserTokensTeble'> class after both dependent classes have been defined.
2024-12-13 19:08:11,525 - contacts.py - global_logger - INFO - contact created with id: 2
2024-12-13 19:09:08,374 - contacts.py - INFO - contact created with id: 3
INFO-2024-12-13 19:09:55,150-contacts.py-contact created with id: 4
ERROR - 2024-12-14 00:36:28,686  -conection_postgres.py - Session rollback, exception: module 'jwt' has no attribute 'encode'
ERROR - 2024-12-14 03:04:00,281  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 03:09:14,818  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 03:09:35,658  -autirisation.py - input RefreshToken != RefreshToken in db, or token not yiet in DB
ERROR - 2024-12-14 03:09:35,658  -autirisation.py - Error pocessing refresh token for user: dimacheban23@meta.ua-401: Interval server error 
ERROR - 2024-12-14 03:09:35,658  -conection_postgres.py - Session rollback, exception: 500: Interval server error 
ERROR - 2024-12-14 09:37:36,776  -autirisation.py - input RefreshToken != RefreshToken in db, or token not yiet in DB
ERROR - 2024-12-14 09:37:36,777  -autirisation.py - Error pocessing refresh token for user: dimacheban23@meta.ua-401: Interval server error 
ERROR - 2024-12-14 09:37:36,777  -conection_postgres.py - Session rollback, exception: 500: Interval server error 
ERROR - 2024-12-14 10:52:13,722  -conection_postgres.py - Session rollback, exception: 401: Invalid pass
ERROR - 2024-12-14 10:52:27,708  -conection_postgres.py - Session rollback, exception: 'coroutine' object is not subscriptable
ERROR - 2024-12-14 10:57:48,312  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
ERROR - 2024-12-14 11:07:08,638  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
ERROR - 2024-12-14 11:07:29,023  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
ERROR - 2024-12-14 11:24:18,114  -conection_postgres.py - Session rollback, exception: type object 'ContactsTable' has no attribute 'user_id'
ERROR - 2024-12-14 11:26:15,011  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 11:26:57,541  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 11:27:01,185  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 11:27:29,859  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 11:27:53,442  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 11:29:54,338  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
ERROR - 2024-12-14 12:18:58,128  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
INFO - 2024-12-14 12:19:32,650  -contacts.py - contact created with id: 5
ERROR - 2024-12-14 12:20:16,186  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
INFO - 2024-12-14 12:21:32,266  -contacts.py - contact created with id: 6
ERROR - 2024-12-14 12:44:00,884  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
ERROR - 2024-12-14 12:44:24,685  -conection_postgres.py - Session rollback, exception: 'JWTService' object has no attribute 'decode_refresh_token'
ERROR - 2024-12-14 12:49:11,012  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
ERROR - 2024-12-14 12:49:45,012  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 12:50:04,998  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 12:50:27,543  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 12:50:47,696  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 12:51:54,383  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
ERROR - 2024-12-14 12:55:20,800  -conection_postgres.py - Session rollback, exception: 404: NOT FOUND
ERROR - 2024-12-14 12:57:48,463  -conection_postgres.py - Session rollback, exception: 401: Could not validate credentials
ERROR - 2024-12-14 13:00:35,359  -conection_postgres.py - Session rollback, exception: 401: Not authenticated
ERROR - 2024-12-14 13:14:35,008  -conection_postgres.py - Session rollback, exception: 401: invalid email
ERROR - 2024-12-14 13:15:05,452  -conection_postgres.py - Session rollback, exception: 401: Account not confirmed, check email
INFO - 2024-12-14 15:44:35,845  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 15:44:35,853  -worker.py - Worker is consuming messages...
INFO - 2024-12-14 15:45:20,233  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 15:45:20,238  -worker.py - Worker is consuming messages...
ERROR - 2024-12-14 15:48:01,716  -conection_postgres.py - Session rollback, exception: 409: Account already exists
ERROR - 2024-12-14 15:49:20,420  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 15:54:06,979  -conection_postgres.py - Session rollback, exception: 409: Account already exists
ERROR - 2024-12-14 15:54:40,935  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 16:34:53,831  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 16:51:10,016  -conection_postgres.py - Session rollback, exception: 409: Account already exists
ERROR - 2024-12-14 16:51:18,148  -conection_postgres.py - Session rollback, exception: 'str' object has no attribute 'base_url'
ERROR - 2024-12-14 16:54:07,999  -conection_postgres.py - Session rollback, exception: 'str' object has no attribute 'base_url'
ERROR - 2024-12-14 16:54:47,445  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-14 16:54:55,296  -email_service.py - Sending email task to RabbitMQ: {'email': 'dark010@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEwQG1ldGEudWEiLCJleHAiOjE3MzQyMzEyOTUsImlhdCI6MTczNDE4ODA5NSwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.tDQQlZITItycU_tGzV692x4fm-gYYzIp8zKL9Yjn9S0', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'} 
INFO - 2024-12-14 16:54:55,304  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 16:54:55,312  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dark010@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEwQG1ldGEudWEiLCJleHAiOjE3MzQyMzEyOTUsImlhdCI6MTczNDE4ODA5NSwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.tDQQlZITItycU_tGzV692x4fm-gYYzIp8zKL9Yjn9S0', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
ERROR - 2024-12-14 16:54:55,314  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x110baa850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x110baa850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x110baa850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

ERROR - 2024-12-14 16:54:56,099  -worker.py - Failed to process message: Server not connected
INFO - 2024-12-14 16:57:24,018  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 16:57:24,025  -worker.py - Worker is consuming messages...
INFO - 2024-12-14 16:57:36,536  -email_service.py - Sending email task to RabbitMQ: {'email': 'dark011@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDExQG1ldGEudWEiLCJleHAiOjE3MzQyMzE0NTYsImlhdCI6MTczNDE4ODI1Niwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.jUmb_BkUQxAfKdB6q4AEmjfR8TLOJcs4SIN90g8o9GY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'} 
INFO - 2024-12-14 16:57:36,541  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 16:57:36,545  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dark011@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDExQG1ldGEudWEiLCJleHAiOjE3MzQyMzE0NTYsImlhdCI6MTczNDE4ODI1Niwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.jUmb_BkUQxAfKdB6q4AEmjfR8TLOJcs4SIN90g8o9GY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
ERROR - 2024-12-14 16:57:36,547  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 16:57:37,286  -worker.py - Failed to process message: Server not connected
INFO - 2024-12-14 17:00:07,403  -email_service.py - Sending email task to RabbitMQ: {'email': 'dark012@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEyQG1ldGEudWEiLCJleHAiOjE3MzQyMzE2MDcsImlhdCI6MTczNDE4ODQwNywic2NvcGUiOiJlbWFpbF90b2tlbiJ9.reuQC63QDUGOYC8UKsF7bHBNLyFrWbof6DBUyqubyHU', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'} 
INFO - 2024-12-14 17:00:07,409  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 17:00:07,416  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dark012@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEyQG1ldGEudWEiLCJleHAiOjE3MzQyMzE2MDcsImlhdCI6MTczNDE4ODQwNywic2NvcGUiOiJlbWFpbF90b2tlbiJ9.reuQC63QDUGOYC8UKsF7bHBNLyFrWbof6DBUyqubyHU', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
ERROR - 2024-12-14 17:00:07,418  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 17:00:08,038  -worker.py - Failed to process message: Server not connected
INFO - 2024-12-14 17:16:44,211  -autirisation.py - starting signup funtion
INFO - 2024-12-14 17:16:44,315  -autirisation.py - User created successfully
INFO - 2024-12-14 17:16:44,320  -autirisation.py - Email token created
INFO - 2024-12-14 17:16:44,321  -users.py - Updating token for user 12
INFO - 2024-12-14 17:16:44,326  -users.py - Query executed for user 12
INFO - 2024-12-14 17:16:44,327  -users.py - New token created for user 12
INFO - 2024-12-14 17:16:44,330  -autirisation.py - token updated in db
INFO - 2024-12-14 17:16:44,330  -email_service.py - Sending email task to RabbitMQ: {'email': 'dark013@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEzQG1ldGEudWEiLCJleHAiOjE3MzQyMzI2MDQsImlhdCI6MTczNDE4OTQwNCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ROOIXjTBU0JIpVipyH4ZP5f1ABca5L4IT6RqRZppJJY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'} 
INFO - 2024-12-14 17:16:44,330  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dark013@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEzQG1ldGEudWEiLCJleHAiOjE3MzQyMzI2MDQsImlhdCI6MTczNDE4OTQwNCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ROOIXjTBU0JIpVipyH4ZP5f1ABca5L4IT6RqRZppJJY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:16:44,336  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 17:16:44,341  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dark013@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEzQG1ldGEudWEiLCJleHAiOjE3MzQyMzI2MDQsImlhdCI6MTczNDE4OTQwNCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ROOIXjTBU0JIpVipyH4ZP5f1ABca5L4IT6RqRZppJJY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:16:44,342  -autirisation.py - Email sent
ERROR - 2024-12-14 17:16:44,343  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-14 17:35:32,404  -worker.py - Starting worker...
INFO - 2024-12-14 17:35:32,419  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 17:35:32,425  -worker.py - Worker is consuming messages...
INFO - 2024-12-14 17:35:32,425  -worker.py - Processing message: b'{"email": "dark013@meta.ua", "username": "Dima", "host": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEzQG1ldGEudWEiLCJleHAiOjE3MzQyMzI2MDQsImlhdCI6MTczNDE4OTQwNCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ROOIXjTBU0JIpVipyH4ZP5f1ABca5L4IT6RqRZppJJY", "queue_name": "confirm_email", "token": "http://127.0.0.1:8000/"}'
INFO - 2024-12-14 17:35:32,425  -worker.py - Message data parsed: {'email': 'dark013@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDEzQG1ldGEudWEiLCJleHAiOjE3MzQyMzI2MDQsImlhdCI6MTczNDE4OTQwNCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ROOIXjTBU0JIpVipyH4ZP5f1ABca5L4IT6RqRZppJJY', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:35:32,425  -worker.py - Processing confirm email message
ERROR - 2024-12-14 17:35:33,063  -worker.py - Failed to process message: Server not connected
INFO - 2024-12-14 17:36:35,975  -worker.py - Starting worker...
INFO - 2024-12-14 17:36:35,987  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 17:36:35,992  -worker.py - Worker is consuming messages...
INFO - 2024-12-14 17:37:40,081  -autirisation.py - starting signup funtion
INFO - 2024-12-14 17:37:40,183  -autirisation.py - User created successfully
INFO - 2024-12-14 17:37:40,197  -autirisation.py - Email token created
INFO - 2024-12-14 17:37:40,197  -users.py - Updating token for user 13
INFO - 2024-12-14 17:37:40,199  -users.py - Query executed for user 13
INFO - 2024-12-14 17:37:40,199  -users.py - New token created for user 13
INFO - 2024-12-14 17:37:40,203  -autirisation.py - token updated in db
INFO - 2024-12-14 17:37:40,203  -email_service.py - Sending email task to RabbitMQ: {'email': 'dark014@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDE0QG1ldGEudWEiLCJleHAiOjE3MzQyMzM4NjAsImlhdCI6MTczNDE5MDY2MCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ALulKQ7G5ZT_qNc2zriH62lIRyGk88doeKQ5ofcv5tA', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'} 
INFO - 2024-12-14 17:37:40,203  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dark014@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDE0QG1ldGEudWEiLCJleHAiOjE3MzQyMzM4NjAsImlhdCI6MTczNDE5MDY2MCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ALulKQ7G5ZT_qNc2zriH62lIRyGk88doeKQ5ofcv5tA', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:37:40,208  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-14 17:37:40,213  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dark014@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDE0QG1ldGEudWEiLCJleHAiOjE3MzQyMzM4NjAsImlhdCI6MTczNDE5MDY2MCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ALulKQ7G5ZT_qNc2zriH62lIRyGk88doeKQ5ofcv5tA', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:37:40,213  -worker.py - Processing message: b'{"email": "dark014@meta.ua", "username": "Dima", "host": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDE0QG1ldGEudWEiLCJleHAiOjE3MzQyMzM4NjAsImlhdCI6MTczNDE5MDY2MCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ALulKQ7G5ZT_qNc2zriH62lIRyGk88doeKQ5ofcv5tA", "queue_name": "confirm_email", "token": "http://127.0.0.1:8000/"}'
INFO - 2024-12-14 17:37:40,213  -worker.py - Message data parsed: {'email': 'dark014@meta.ua', 'username': 'Dima', 'host': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrMDE0QG1ldGEudWEiLCJleHAiOjE3MzQyMzM4NjAsImlhdCI6MTczNDE5MDY2MCwic2NvcGUiOiJlbWFpbF90b2tlbiJ9.ALulKQ7G5ZT_qNc2zriH62lIRyGk88doeKQ5ofcv5tA', 'queue_name': 'confirm_email', 'token': 'http://127.0.0.1:8000/'}
INFO - 2024-12-14 17:37:40,213  -worker.py - Processing confirm email message
INFO - 2024-12-14 17:37:40,214  -autirisation.py - Email sent
ERROR - 2024-12-14 17:37:40,214  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 17:37:40,829  -worker.py - Failed to process message: Server not connected
INFO - 2024-12-14 17:39:44,006  -autirisation.py - Email token created
INFO - 2024-12-14 17:40:49,849  -autirisation.py - Email token created
INFO - 2024-12-14 17:43:33,651  -users.py - Updating token for user 16
INFO - 2024-12-14 17:43:33,654  -users.py - Query executed for user 16
INFO - 2024-12-14 17:43:33,654  -users.py - New token created for user 16
ERROR - 2024-12-14 17:43:33,658  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x107c41fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x107c41fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x107c41fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

ERROR - 2024-12-14 17:51:08,430  -conection_postgres.py - Session rollback, exception: Can't find strategy (('lazy', 'joinedload'),) for ContactsTable.user
ERROR - 2024-12-14 17:54:33,052  -conection_postgres.py - Session rollback, exception: module 'src.repository.users' has no attribute 'updat_token'
WARNING - 2024-12-14 17:54:54,982  -autirisation.py - user already exists
ERROR - 2024-12-14 17:54:54,983  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-14 17:55:00,887  -users.py - Updating token for user 18
INFO - 2024-12-14 17:55:00,893  -users.py - Query executed for user 18
INFO - 2024-12-14 17:55:00,893  -users.py - New token created for user 18
ERROR - 2024-12-14 17:55:00,898  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x105f56850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x105f56850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x105f56850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

INFO - 2024-12-14 18:02:41,644  -users.py - Updating token for user 19
INFO - 2024-12-14 18:02:41,651  -users.py - Query executed for user 19
INFO - 2024-12-14 18:02:41,652  -users.py - New token created for user 19
ERROR - 2024-12-14 18:02:41,656  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x118299fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x118299fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x118299fd0>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

ERROR - 2024-12-14 18:03:22,581  -conection_postgres.py - Session rollback, exception: 'UserSchema' object has no attribute 'id'
ERROR - 2024-12-14 18:05:14,426  -conection_postgres.py - Session rollback, exception: cannot access local variable 'new_user' where it is not associated with a value
ERROR - 2024-12-14 18:12:34,618  -conection_postgres.py - Session rollback, exception: cannot access local variable 'new_user' where it is not associated with a value
ERROR - 2024-12-14 18:13:15,374  -conection_postgres.py - Session rollback, exception: cannot access local variable 'new_user' where it is not associated with a value
ERROR - 2024-12-14 18:15:43,647  -conection_postgres.py - Session rollback, exception: 'UserSchema' object has no attribute 'id'
WARNING - 2024-12-14 18:16:01,160  -autirisation.py - user already exists
ERROR - 2024-12-14 18:16:01,160  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-14 18:16:07,902  -users.py - Updating token for user 23
INFO - 2024-12-14 18:16:07,907  -users.py - Query executed for user 23
INFO - 2024-12-14 18:16:07,907  -users.py - New token created for user 23
ERROR - 2024-12-14 18:16:07,911  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x11a1ae850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x11a1ae850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x11a1ae850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

INFO - 2024-12-14 20:58:35,027  -users.py - Updating token for user 24
INFO - 2024-12-14 20:58:35,032  -users.py - Query executed for user 24
INFO - 2024-12-14 20:58:35,032  -users.py - New token created for user 24
ERROR - 2024-12-14 20:58:35,035  -users.py - Failed to update user's token: Class 'sqlalchemy.orm.decl_api.DeclarativeAttributeIntercept' is not mapped; was a class (src.entity.models.UserTokensTable) supplied where an instance was required?/email_token
ERROR - 2024-12-14 20:58:35,035  -conection_postgres.py - Session rollback, exception: Class 'sqlalchemy.orm.decl_api.DeclarativeAttributeIntercept' is not mapped; was a class (src.entity.models.UserTokensTable) supplied where an instance was required?
WARNING - 2024-12-14 20:59:31,455  -autirisation.py - user already exists
ERROR - 2024-12-14 20:59:31,456  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-14 20:59:39,089  -users.py - Updating token for user 25
INFO - 2024-12-14 20:59:39,094  -users.py - Query executed for user 25
INFO - 2024-12-14 20:59:39,095  -users.py - New token created for user 25
ERROR - 2024-12-14 20:59:39,099  -conection_postgres.py - Session rollback, exception: 1 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x106016850>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

INFO - 2024-12-14 21:08:15,899  -users.py - Updating token for user 26
INFO - 2024-12-14 21:08:15,904  -users.py - Query executed for user 26
INFO - 2024-12-14 21:08:15,904  -users.py - New token created for user 26
ERROR - 2024-12-14 21:08:15,909  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-14 21:10:32,894  -conection_postgres.py - Session rollback, exception: name 'reqw' is not defined
WARNING - 2024-12-14 21:11:02,403  -autirisation.py - user already exists
ERROR - 2024-12-14 21:11:02,403  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-15 01:04:29,670  -users.py - Updating token for user 30
INFO - 2024-12-15 01:04:29,676  -users.py - Query executed for user 30
INFO - 2024-12-15 01:04:29,676  -users.py - New token created for user 30
ERROR - 2024-12-15 01:04:29,681  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
WARNING - 2024-12-15 01:08:58,673  -autirisation.py - user already exists
ERROR - 2024-12-15 01:08:58,674  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-15 01:09:05,395  -users.py - Updating token for user 31
INFO - 2024-12-15 01:09:05,401  -users.py - Query executed for user 31
INFO - 2024-12-15 01:09:05,401  -users.py - New token created for user 31
ERROR - 2024-12-15 01:09:05,405  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 01:14:02,495  -users.py - Updating token for user 32
INFO - 2024-12-15 01:14:02,504  -users.py - Query executed for user 32
ERROR - 2024-12-15 01:14:02,505  -users.py - Failed to update user's token: object NoneType can't be used in 'await' expression/email_token
ERROR - 2024-12-15 01:14:02,505  -conection_postgres.py - Session rollback, exception: object NoneType can't be used in 'await' expression
INFO - 2024-12-15 01:17:02,220  -users.py - Updating token for user 33
INFO - 2024-12-15 01:17:02,224  -users.py - Query executed for user 33
INFO - 2024-12-15 01:17:02,226  -users.py - New token created for user 33
ERROR - 2024-12-15 01:17:02,227  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 01:18:18,603  -conection_postgres.py - Session rollback, exception: 'function' object has no attribute 'info'
INFO - 2024-12-15 01:18:56,472  -autirisation.py - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJrNkBtZXRhLnVhIiwiZXhwIjoxNzM0MjYxNTM2LCJpYXQiOjE3MzQyMTgzMzYsInNjb3BlIjoiZW1haWxfdG9rZW4ifQ._5t0btgrXS4hBwuYKTUZRU1CI40c72qI4xB4BOqQrak
INFO - 2024-12-15 01:22:10,464  -users.py - New token created for user 36
ERROR - 2024-12-15 01:22:10,466  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 01:22:40,147  -conection_postgres.py - Session rollback, exception: 401: Account not confirmed, check email
INFO - 2024-12-15 01:23:22,307  -users.py - Token updated for user 6
INFO - 2024-12-15 01:23:35,101  -users.py - Token updated for user 6
ERROR - 2024-12-15 01:32:46,685  -conection_postgres.py - Session rollback, exception: 'Depends' object has no attribute 'execute'
INFO - 2024-12-15 01:33:28,698  -users.py - New token created for user 38
ERROR - 2024-12-15 01:33:28,703  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 01:34:45,003  -users.py - New token created for user 39
ERROR - 2024-12-15 01:34:45,008  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 01:38:51,994  -autirisation.py - <src.entity.models.UsersTable object at 0x104d39fd0>
INFO - 2024-12-15 01:39:55,031  -autirisation.py - dark98@meta.ua
ERROR - 2024-12-15 01:41:34,945  -conection_postgres.py - Session rollback, exception: Instance '<UsersTable at 0x10a39dfd0>' is not persistent within this Session
INFO - 2024-12-15 01:42:21,636  -autirisation.py - dark97@meta.ua
INFO - 2024-12-15 01:42:21,644  -users.py - New token created for user 42
ERROR - 2024-12-15 01:42:21,651  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 01:44:25,847  -autirisation.py - dark1@meta.ua
INFO - 2024-12-15 01:44:25,852  -users.py - New token created for user 43
ERROR - 2024-12-15 01:44:25,856  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 01:45:07,245  -autirisation.py - dark2@meta.ua
INFO - 2024-12-15 01:45:07,252  -users.py - New token created for user 44
ERROR - 2024-12-15 01:45:07,256  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 01:50:34,121  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:03:15,858  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
WARNING - 2024-12-15 02:03:34,312  -autirisation.py - user already exists
ERROR - 2024-12-15 02:03:34,312  -conection_postgres.py - Session rollback, exception: 409: Account already exists
ERROR - 2024-12-15 02:03:38,809  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:05:14,141  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:21:21,850  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:21:57,146  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:22:38,152  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 02:23:21,157  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
WARNING - 2024-12-15 02:24:22,306  -autirisation.py - user already exists
ERROR - 2024-12-15 02:24:22,307  -conection_postgres.py - Session rollback, exception: 409: Account already exists
ERROR - 2024-12-15 02:24:28,110  -conection_postgres.py - Session rollback, exception: AsyncSession.refresh() missing 1 required positional argument: 'instance'
ERROR - 2024-12-15 02:25:06,097  -conection_postgres.py - Session rollback, exception: Instance '<UsersTable at 0x106b9a120>' is not persistent within this Session
ERROR - 2024-12-15 02:26:19,599  -conection_postgres.py - Session rollback, exception: Instance '<UsersTable at 0x10887a120>' is not persistent within this Session
ERROR - 2024-12-15 02:26:43,541  -conection_postgres.py - Session rollback, exception: Instance '<UsersTable at 0x108872120>' is not persistent within this Session
INFO - 2024-12-15 02:29:04,919  -autirisation.py - dark15@meta.ua
INFO - 2024-12-15 02:29:23,635  -autirisation.py - dark16@meta.ua
ERROR - 2024-12-15 02:29:23,644  -conection_postgres.py - Session rollback, exception: 3 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x10672e120>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'username'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x10672e120>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'email'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)", 'input': <src.entity.models.UsersTable object at 0x10672e120>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)"}}

INFO - 2024-12-15 02:36:50,761  -autirisation.py - dark17@meta.ua
ERROR - 2024-12-15 02:36:50,775  -conection_postgres.py - Session rollback, exception: You must set the config attribute `from_attributes=True` to use from_orm
INFO - 2024-12-15 02:39:33,852  -autirisation.py - dark18@meta.ua
ERROR - 2024-12-15 02:39:33,860  -conection_postgres.py - Session rollback, exception: You must set the config attribute `from_attributes=True` to use from_orm
WARNING - 2024-12-15 02:40:00,294  -autirisation.py - user already exists
ERROR - 2024-12-15 02:40:00,294  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-15 02:40:05,114  -autirisation.py - dark19@meta.ua
ERROR - 2024-12-15 02:40:05,123  -conection_postgres.py - Session rollback, exception: 3 validation errors for UserResponse
id
  Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<src.entity.models.UsersT...e object at 0x105fbe350>, input_type=UsersTable]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
username
  Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<src.entity.models.UsersT...e object at 0x105fbe350>, input_type=UsersTable]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
email
  Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<src.entity.models.UsersT...e object at 0x105fbe350>, input_type=UsersTable]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
INFO - 2024-12-15 02:42:20,144  -autirisation.py - dark20@meta.ua
ERROR - 2024-12-15 02:42:20,150  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
INFO - 2024-12-15 02:42:47,476  -autirisation.py - dark21@meta.ua
INFO - 2024-12-15 02:44:02,662  -autirisation.py - dark21@meta.ua
INFO - 2024-12-15 02:45:22,037  -autirisation.py - dark22@meta.ua
ERROR - 2024-12-15 02:45:22,040  -users.py - Failed to update user token: 'UsersTable' object is not subscriptable/email_token
INFO - 2024-12-15 02:47:24,712  -autirisation.py - dark23@meta.ua
ERROR - 2024-12-15 02:47:24,717  -users.py - Failed to update user's token: 'UsersTable' object is not subscriptable/email_token
ERROR - 2024-12-15 02:47:24,717  -conection_postgres.py - Session rollback, exception: 'UsersTable' object is not subscriptable
INFO - 2024-12-15 02:47:45,357  -autirisation.py - dark24@meta.ua
ERROR - 2024-12-15 02:47:45,369  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
WARNING - 2024-12-15 02:48:27,501  -autirisation.py - user already exists
ERROR - 2024-12-15 02:48:27,501  -conection_postgres.py - Session rollback, exception: 409: Account already exists
INFO - 2024-12-15 02:48:31,915  -autirisation.py - dark25@meta.ua
INFO - 2024-12-15 02:49:00,360  -autirisation.py - dark26@meta.ua
INFO - 2024-12-15 11:46:18,542  -worker.py - Starting worker...
INFO - 2024-12-15 11:46:18,557  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 11:46:18,565  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 11:46:24,320  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDI5OTE4NCwiaWF0IjoxNzM0MjU1OTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GqiPu2cC27_uARMI1FHsstIOHYzRHIb0K0ag3ktFZOg'} 
INFO - 2024-12-15 11:46:24,320  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDI5OTE4NCwiaWF0IjoxNzM0MjU1OTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GqiPu2cC27_uARMI1FHsstIOHYzRHIb0K0ag3ktFZOg'}
INFO - 2024-12-15 11:46:24,328  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 11:46:24,332  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDI5OTE4NCwiaWF0IjoxNzM0MjU1OTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GqiPu2cC27_uARMI1FHsstIOHYzRHIb0K0ag3ktFZOg"}'
INFO - 2024-12-15 11:46:24,332  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDI5OTE4NCwiaWF0IjoxNzM0MjU1OTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GqiPu2cC27_uARMI1FHsstIOHYzRHIb0K0ag3ktFZOg'}
INFO - 2024-12-15 11:46:24,332  -worker.py - Processing confirm email message
INFO - 2024-12-15 11:46:24,332  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDI5OTE4NCwiaWF0IjoxNzM0MjU1OTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GqiPu2cC27_uARMI1FHsstIOHYzRHIb0K0ag3ktFZOg'}
INFO - 2024-12-15 11:46:25,782  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 12:28:55,371  -worker.py - Starting worker...
INFO - 2024-12-15 12:28:55,385  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 12:28:55,391  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 12:29:44,633  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMTc4NCwiaWF0IjoxNzM0MjU4NTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.niePbKkCumOJw5NEnfi9u7QazCqN4LP-MIuFK7czy_g'} 
INFO - 2024-12-15 12:29:44,634  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMTc4NCwiaWF0IjoxNzM0MjU4NTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.niePbKkCumOJw5NEnfi9u7QazCqN4LP-MIuFK7czy_g'}
INFO - 2024-12-15 12:29:44,644  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 12:29:44,650  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMTc4NCwiaWF0IjoxNzM0MjU4NTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.niePbKkCumOJw5NEnfi9u7QazCqN4LP-MIuFK7czy_g'}
INFO - 2024-12-15 12:29:44,651  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMTc4NCwiaWF0IjoxNzM0MjU4NTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.niePbKkCumOJw5NEnfi9u7QazCqN4LP-MIuFK7czy_g"}'
INFO - 2024-12-15 12:29:44,651  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMTc4NCwiaWF0IjoxNzM0MjU4NTg0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.niePbKkCumOJw5NEnfi9u7QazCqN4LP-MIuFK7czy_g'}
INFO - 2024-12-15 12:29:44,651  -worker.py - Processing confirm email message
INFO - 2024-12-15 12:29:45,818  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
ERROR - 2024-12-15 12:30:10,938  -conection_postgres.py - Session rollback, exception: module 'src.repository.users' has no attribute 'confirmed_email'
ERROR - 2024-12-15 12:32:06,731  -users.py - Failed to update user's token: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)/email_token
ERROR - 2024-12-15 12:32:06,731  -conection_postgres.py - Session rollback, exception: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
ERROR - 2024-12-15 12:34:21,164  -users.py - Failed to update user's token: cannot access local variable 'new_token' where it is not associated with a value/email_token
ERROR - 2024-12-15 12:34:21,165  -conection_postgres.py - Session rollback, exception: cannot access local variable 'new_token' where it is not associated with a value
ERROR - 2024-12-15 12:37:47,099  -users.py - Failed to update user's token: Class 'builtins.NoneType' is not mapped/email_token
ERROR - 2024-12-15 12:37:47,100  -conection_postgres.py - Session rollback, exception: Class 'builtins.NoneType' is not mapped
INFO - 2024-12-15 12:38:54,938  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMjMzNCwiaWF0IjoxNzM0MjU5MTM0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.Y9N_4wUASfUNkxMNIJrDHS1FXLmXyoV5nbPR37L_o-Q'} 
INFO - 2024-12-15 12:38:54,938  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMjMzNCwiaWF0IjoxNzM0MjU5MTM0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.Y9N_4wUASfUNkxMNIJrDHS1FXLmXyoV5nbPR37L_o-Q'}
INFO - 2024-12-15 12:38:54,946  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 12:38:54,951  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMjMzNCwiaWF0IjoxNzM0MjU5MTM0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.Y9N_4wUASfUNkxMNIJrDHS1FXLmXyoV5nbPR37L_o-Q'}
INFO - 2024-12-15 12:38:54,952  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMjMzNCwiaWF0IjoxNzM0MjU5MTM0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.Y9N_4wUASfUNkxMNIJrDHS1FXLmXyoV5nbPR37L_o-Q"}'
INFO - 2024-12-15 12:38:54,952  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwMjMzNCwiaWF0IjoxNzM0MjU5MTM0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.Y9N_4wUASfUNkxMNIJrDHS1FXLmXyoV5nbPR37L_o-Q'}
INFO - 2024-12-15 12:38:54,952  -worker.py - Processing confirm email message
INFO - 2024-12-15 12:38:56,052  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 12:43:22,587  -autirisation.py - dima open confirm email link 
ERROR - 2024-12-15 13:19:36,416  -conection_postgres.py - Session rollback, exception: 401: invalid email
INFO - 2024-12-15 13:19:46,210  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDc4NiwiaWF0IjoxNzM0MjYxNTg2LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.hCilEWxg67KZtvBp0CJ5jzdZZomGuDul_6d-o0fUjPY'} 
INFO - 2024-12-15 13:19:46,210  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDc4NiwiaWF0IjoxNzM0MjYxNTg2LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.hCilEWxg67KZtvBp0CJ5jzdZZomGuDul_6d-o0fUjPY'}
INFO - 2024-12-15 13:19:46,219  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 13:19:46,225  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDc4NiwiaWF0IjoxNzM0MjYxNTg2LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.hCilEWxg67KZtvBp0CJ5jzdZZomGuDul_6d-o0fUjPY'}
INFO - 2024-12-15 13:19:46,226  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDc4NiwiaWF0IjoxNzM0MjYxNTg2LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.hCilEWxg67KZtvBp0CJ5jzdZZomGuDul_6d-o0fUjPY"}'
INFO - 2024-12-15 13:19:46,226  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDc4NiwiaWF0IjoxNzM0MjYxNTg2LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.hCilEWxg67KZtvBp0CJ5jzdZZomGuDul_6d-o0fUjPY'}
INFO - 2024-12-15 13:19:46,226  -worker.py - Processing confirm email message
INFO - 2024-12-15 13:19:47,640  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 13:22:12,203  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDkzMiwiaWF0IjoxNzM0MjYxNzMyLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1HQgHPc9JT6IDsWyFdfe-CnALxM4CgFQgTVAu8x47sk'} 
INFO - 2024-12-15 13:22:12,204  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDkzMiwiaWF0IjoxNzM0MjYxNzMyLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1HQgHPc9JT6IDsWyFdfe-CnALxM4CgFQgTVAu8x47sk'}
INFO - 2024-12-15 13:22:12,214  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 13:22:12,219  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDkzMiwiaWF0IjoxNzM0MjYxNzMyLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1HQgHPc9JT6IDsWyFdfe-CnALxM4CgFQgTVAu8x47sk'}
INFO - 2024-12-15 13:22:12,220  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDkzMiwiaWF0IjoxNzM0MjYxNzMyLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1HQgHPc9JT6IDsWyFdfe-CnALxM4CgFQgTVAu8x47sk"}'
INFO - 2024-12-15 13:22:12,220  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNDkzMiwiaWF0IjoxNzM0MjYxNzMyLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1HQgHPc9JT6IDsWyFdfe-CnALxM4CgFQgTVAu8x47sk'}
INFO - 2024-12-15 13:22:12,220  -worker.py - Processing confirm email message
INFO - 2024-12-15 13:22:13,459  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 13:30:47,455  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTQ0NywiaWF0IjoxNzM0MjYyMjQ3LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.joEx7h3Q1sT2NW-Nn32-7zXLPNZBh7sStpfGxV3GoYM'} 
INFO - 2024-12-15 13:30:47,455  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTQ0NywiaWF0IjoxNzM0MjYyMjQ3LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.joEx7h3Q1sT2NW-Nn32-7zXLPNZBh7sStpfGxV3GoYM'}
INFO - 2024-12-15 13:30:47,462  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 13:30:47,467  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTQ0NywiaWF0IjoxNzM0MjYyMjQ3LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.joEx7h3Q1sT2NW-Nn32-7zXLPNZBh7sStpfGxV3GoYM'}
INFO - 2024-12-15 13:30:47,468  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTQ0NywiaWF0IjoxNzM0MjYyMjQ3LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.joEx7h3Q1sT2NW-Nn32-7zXLPNZBh7sStpfGxV3GoYM"}'
INFO - 2024-12-15 13:30:47,469  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTQ0NywiaWF0IjoxNzM0MjYyMjQ3LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.joEx7h3Q1sT2NW-Nn32-7zXLPNZBh7sStpfGxV3GoYM'}
INFO - 2024-12-15 13:30:47,469  -worker.py - Processing confirm email message
INFO - 2024-12-15 13:30:48,683  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 13:35:31,232  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTczMSwiaWF0IjoxNzM0MjYyNTMxLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.VGcn59AamWQxV3_2JQfeWWlvJvQhcmZ6f10JA6KRSpk'} 
INFO - 2024-12-15 13:35:31,232  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTczMSwiaWF0IjoxNzM0MjYyNTMxLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.VGcn59AamWQxV3_2JQfeWWlvJvQhcmZ6f10JA6KRSpk'}
INFO - 2024-12-15 13:35:31,240  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 13:35:31,245  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTczMSwiaWF0IjoxNzM0MjYyNTMxLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.VGcn59AamWQxV3_2JQfeWWlvJvQhcmZ6f10JA6KRSpk'}
INFO - 2024-12-15 13:35:31,246  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTczMSwiaWF0IjoxNzM0MjYyNTMxLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.VGcn59AamWQxV3_2JQfeWWlvJvQhcmZ6f10JA6KRSpk"}'
INFO - 2024-12-15 13:35:31,246  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwNTczMSwiaWF0IjoxNzM0MjYyNTMxLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.VGcn59AamWQxV3_2JQfeWWlvJvQhcmZ6f10JA6KRSpk'}
INFO - 2024-12-15 13:35:31,246  -worker.py - Processing confirm email message
INFO - 2024-12-15 13:35:32,402  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 14:16:40,226  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwODIwMCwiaWF0IjoxNzM0MjY1MDAwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GR9a9ZQtd54Jo0mbPZe40YvHCRO7zP5We27kb-bZXbA'} 
INFO - 2024-12-15 14:16:40,227  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwODIwMCwiaWF0IjoxNzM0MjY1MDAwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GR9a9ZQtd54Jo0mbPZe40YvHCRO7zP5We27kb-bZXbA'}
INFO - 2024-12-15 14:16:40,236  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 14:16:40,242  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwODIwMCwiaWF0IjoxNzM0MjY1MDAwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GR9a9ZQtd54Jo0mbPZe40YvHCRO7zP5We27kb-bZXbA'}
INFO - 2024-12-15 14:16:40,244  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwODIwMCwiaWF0IjoxNzM0MjY1MDAwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GR9a9ZQtd54Jo0mbPZe40YvHCRO7zP5We27kb-bZXbA"}'
INFO - 2024-12-15 14:16:40,245  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMwODIwMCwiaWF0IjoxNzM0MjY1MDAwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.GR9a9ZQtd54Jo0mbPZe40YvHCRO7zP5We27kb-bZXbA'}
INFO - 2024-12-15 14:16:40,245  -worker.py - Processing confirm email message
INFO - 2024-12-15 14:16:41,987  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 15:12:24,163  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMTU0NCwiaWF0IjoxNzM0MjY4MzQ0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.ykznb6_7cZpRLbkHZWM2lJAvL5C2jC_Oa_Db3I5sPtA'} 
INFO - 2024-12-15 15:12:24,164  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMTU0NCwiaWF0IjoxNzM0MjY4MzQ0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.ykznb6_7cZpRLbkHZWM2lJAvL5C2jC_Oa_Db3I5sPtA'}
INFO - 2024-12-15 15:12:24,171  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 15:12:24,178  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMTU0NCwiaWF0IjoxNzM0MjY4MzQ0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.ykznb6_7cZpRLbkHZWM2lJAvL5C2jC_Oa_Db3I5sPtA'}
INFO - 2024-12-15 15:12:24,179  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMTU0NCwiaWF0IjoxNzM0MjY4MzQ0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.ykznb6_7cZpRLbkHZWM2lJAvL5C2jC_Oa_Db3I5sPtA"}'
INFO - 2024-12-15 15:12:24,180  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMTU0NCwiaWF0IjoxNzM0MjY4MzQ0LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.ykznb6_7cZpRLbkHZWM2lJAvL5C2jC_Oa_Db3I5sPtA'}
INFO - 2024-12-15 15:12:24,180  -worker.py - Processing confirm email message
INFO - 2024-12-15 15:12:25,680  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 15:24:19,870  -users.py - user_name open verifivation email
INFO - 2024-12-15 15:25:09,586  -users.py - dima open verifivation email
INFO - 2024-12-15 15:26:50,945  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMjQxMCwiaWF0IjoxNzM0MjY5MjEwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.MiD-6iBsXxWyLb6faHAWBjEDiyTzUgb_N1NvPk4FChU'} 
INFO - 2024-12-15 15:26:50,946  -produser.py - Preparing to send message to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMjQxMCwiaWF0IjoxNzM0MjY5MjEwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.MiD-6iBsXxWyLb6faHAWBjEDiyTzUgb_N1NvPk4FChU'}
INFO - 2024-12-15 15:26:50,956  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 15:26:50,967  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email': {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMjQxMCwiaWF0IjoxNzM0MjY5MjEwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.MiD-6iBsXxWyLb6faHAWBjEDiyTzUgb_N1NvPk4FChU'}
INFO - 2024-12-15 15:26:50,968  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "confirm_email", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMjQxMCwiaWF0IjoxNzM0MjY5MjEwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.MiD-6iBsXxWyLb6faHAWBjEDiyTzUgb_N1NvPk4FChU"}'
INFO - 2024-12-15 15:26:50,969  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxMjQxMCwiaWF0IjoxNzM0MjY5MjEwLCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.MiD-6iBsXxWyLb6faHAWBjEDiyTzUgb_N1NvPk4FChU'}
INFO - 2024-12-15 15:26:50,969  -worker.py - Processing confirm email message
INFO - 2024-12-15 15:26:52,477  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 15:29:46,262  -users.py - test open verifivation email
INFO - 2024-12-15 16:14:22,427  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTI2MiwiaWF0IjoxNzM0MjcyMDYyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.iBTh_f0Y3fRsSAv7pKgK4B1U3r0ZLTscp_z6JbLRmI4'} 
INFO - 2024-12-15 16:14:22,427  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:14:22,433  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:14:22,438  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:14:22,439  -worker.py - Processing message: b'{"email": "dimacheban23@meta.ua", "username": "test", "host": "http://127.0.0.1:8000/", "queue_name": "reset_password", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTI2MiwiaWF0IjoxNzM0MjcyMDYyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.iBTh_f0Y3fRsSAv7pKgK4B1U3r0ZLTscp_z6JbLRmI4"}'
INFO - 2024-12-15 16:14:22,439  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTI2MiwiaWF0IjoxNzM0MjcyMDYyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.iBTh_f0Y3fRsSAv7pKgK4B1U3r0ZLTscp_z6JbLRmI4'}
INFO - 2024-12-15 16:14:22,439  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:14:22,441  -worker.py - Failed to process message: reset_password_email.html
INFO - 2024-12-15 16:16:51,155  -worker.py - Starting worker...
INFO - 2024-12-15 16:16:51,166  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:16:51,172  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 16:16:56,479  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTQxNiwiaWF0IjoxNzM0MjcyMjE2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.SqCRrx57HNTMQgzCe_68h9Ftlu4VaUzaxzQycNIxyRc'} 
INFO - 2024-12-15 16:16:56,479  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:16:56,486  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:16:56,491  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:16:56,491  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTQxNiwiaWF0IjoxNzM0MjcyMjE2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.SqCRrx57HNTMQgzCe_68h9Ftlu4VaUzaxzQycNIxyRc'}
INFO - 2024-12-15 16:16:56,491  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:16:57,644  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 16:21:11,844  -worker.py - Starting worker...
INFO - 2024-12-15 16:21:11,854  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:21:11,859  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 16:21:42,933  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTcwMiwiaWF0IjoxNzM0MjcyNTAyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.K0v1S0qzLKyFEpQhwycLe_zBooF32oYVuY1icrWzPZg'} 
INFO - 2024-12-15 16:21:42,933  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:21:42,941  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:21:42,949  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:21:42,949  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNTcwMiwiaWF0IjoxNzM0MjcyNTAyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.K0v1S0qzLKyFEpQhwycLe_zBooF32oYVuY1icrWzPZg'}
INFO - 2024-12-15 16:21:42,949  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:21:44,632  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 16:22:01,336  -users.py - test open verifivation email
INFO - 2024-12-15 16:26:58,973  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjAxOCwiaWF0IjoxNzM0MjcyODE4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.46NrYYN5YhfVTI_Q589BmN6AiXyo1r6HP5yLJsHltUY'} 
INFO - 2024-12-15 16:26:58,973  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:26:58,978  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:26:58,982  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:26:58,982  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjAxOCwiaWF0IjoxNzM0MjcyODE4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.46NrYYN5YhfVTI_Q589BmN6AiXyo1r6HP5yLJsHltUY'}
INFO - 2024-12-15 16:26:58,982  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:27:00,140  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 16:27:16,326  -worker.py - Starting worker...
INFO - 2024-12-15 16:27:16,337  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:27:16,343  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 16:27:20,200  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjA0MCwiaWF0IjoxNzM0MjcyODQwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.KdD_DxR6CfvxUOViAm2w7IaqKJJDfVp7mv3JOgYYGnY'} 
INFO - 2024-12-15 16:27:20,200  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:27:20,207  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:27:20,214  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:27:20,214  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjA0MCwiaWF0IjoxNzM0MjcyODQwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.KdD_DxR6CfvxUOViAm2w7IaqKJJDfVp7mv3JOgYYGnY'}
INFO - 2024-12-15 16:27:20,215  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:27:21,339  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 16:39:09,797  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjc0OSwiaWF0IjoxNzM0MjczNTQ5LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.3LPsRHTLRI4ViaZcRRhgm-VcB942IsdLdshyGTWDbsM'} 
INFO - 2024-12-15 16:39:09,797  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:39:09,804  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:39:09,809  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:39:09,810  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjc0OSwiaWF0IjoxNzM0MjczNTQ5LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.3LPsRHTLRI4ViaZcRRhgm-VcB942IsdLdshyGTWDbsM'}
INFO - 2024-12-15 16:39:09,810  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:39:11,090  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 16:39:18,855  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjc1OCwiaWF0IjoxNzM0MjczNTU4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.vDvdDx3GPjB7lUNQra8OvY6cD-yRo3sbZtSjO9kB-Cc'} 
INFO - 2024-12-15 16:39:18,855  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:39:18,862  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:39:18,867  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 16:39:24,300  -worker.py - Starting worker...
INFO - 2024-12-15 16:39:24,313  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:39:24,318  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 16:39:24,318  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjc1OCwiaWF0IjoxNzM0MjczNTU4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.vDvdDx3GPjB7lUNQra8OvY6cD-yRo3sbZtSjO9kB-Cc'}
INFO - 2024-12-15 16:39:24,318  -worker.py - Processing reset password message
ERROR - 2024-12-15 16:39:25,408  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
ERROR - 2024-12-15 16:45:04,970  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
INFO - 2024-12-15 16:48:03,744  -users.py - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNjc1OCwiaWF0IjoxNzM0MjczNTU4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.vDvdDx3GPjB7lUNQra8OvY6cD-yRo3sbZtSjO9kB-Cc open verifivation email
ERROR - 2024-12-15 16:48:58,728  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
ERROR - 2024-12-15 16:49:59,794  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
INFO - 2024-12-15 16:54:18,450  -email_service.py - token type email_token
INFO - 2024-12-15 16:54:18,460  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNzY1OCwiaWF0IjoxNzM0Mjc0NDU4LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1F42be_zMtIUSCuIGFZ9MOgDG05nKWYiXDAbXjjsQRY'} 
INFO - 2024-12-15 16:54:18,460  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 16:54:18,467  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 16:54:18,472  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email
INFO - 2024-12-15 16:54:18,473  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxNzY1OCwiaWF0IjoxNzM0Mjc0NDU4LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.1F42be_zMtIUSCuIGFZ9MOgDG05nKWYiXDAbXjjsQRY'}
INFO - 2024-12-15 16:54:18,473  -worker.py - Processing confirm email message
INFO - 2024-12-15 16:54:19,600  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-15 17:02:12,720  -users.py - Get curent user finifsh test
INFO - 2024-12-15 17:02:12,723  -email_service.py - token type reset_password_token
INFO - 2024-12-15 17:02:12,724  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxODEzMiwiaWF0IjoxNzM0Mjc0OTMyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.a1CLAcKQA2gdWPY1xYy6bW3zotpNfoh5b1pYxEFWA9U
INFO - 2024-12-15 17:02:57,455  -users.py - Get curent user finifsh test
INFO - 2024-12-15 17:02:57,457  -email_service.py - token type reset_password_token
INFO - 2024-12-15 17:02:57,457  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMxODE3NywiaWF0IjoxNzM0Mjc0OTc3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.fwYz9gcfFMX8mwgL7p5QbcDlgY2JsbDwpADm3SYqSvs
ERROR - 2024-12-15 17:03:49,389  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
ERROR - 2024-12-15 17:05:16,826  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
INFO - 2024-12-15 17:06:22,911  -users.py - start ger email
ERROR - 2024-12-15 17:06:22,917  -conection_postgres.py - Session rollback, exception: 401: Invalid scope for token
INFO - 2024-12-15 17:07:21,691  -users.py - get email from token dimacheban23@meta.ua
INFO - 2024-12-15 17:07:21,741  -users.py - test reset password del token reser password
INFO - 2024-12-15 17:29:01,196  -users.py - True Verify password
INFO - 2024-12-15 17:37:48,438  -users.py - test reset password
INFO - 2024-12-15 17:37:48,450  -users.py - test del reset_password_token
INFO - 2024-12-15 17:38:34,939  -users.py - test reset password
INFO - 2024-12-15 17:38:34,950  -users.py - test del reset_password_token
INFO - 2024-12-15 19:01:13,166  -worker.py - Starting worker...
INFO - 2024-12-15 19:01:13,181  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:01:13,186  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 19:01:44,520  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:01:44,524  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:01:44,524  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNTMwNCwiaWF0IjoxNzM0MjgyMTA0LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.eTsIKkkjYsg6rsn6OA3XU1FIYwYEHmJwMok_kgfGAD4
INFO - 2024-12-15 19:02:01,668  -users.py - test open verifivation email
INFO - 2024-12-15 19:12:51,416  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:12:51,421  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:12:51,421  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNTk3MSwiaWF0IjoxNzM0MjgyNzcxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.mnh26N1qsn4lQQ25Bnh8JqcLknGNMJ0gTNEAkBoblk4
INFO - 2024-12-15 19:12:51,434  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNTk3MSwiaWF0IjoxNzM0MjgyNzcxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.mnh26N1qsn4lQQ25Bnh8JqcLknGNMJ0gTNEAkBoblk4'} 
INFO - 2024-12-15 19:12:51,434  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:12:51,442  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:12:51,448  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 19:12:51,451  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNTk3MSwiaWF0IjoxNzM0MjgyNzcxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.mnh26N1qsn4lQQ25Bnh8JqcLknGNMJ0gTNEAkBoblk4'}
INFO - 2024-12-15 19:12:51,452  -worker.py - Processing reset password message
ERROR - 2024-12-15 19:12:51,463  -worker.py - Failed to process message: Exception raised The start_tls and use_tls options are not compatible., check your credentials or email service configuration
INFO - 2024-12-15 19:14:30,242  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:14:30,242  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:14:30,242  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA3MCwiaWF0IjoxNzM0MjgyODcwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.wnYOrgjUC3uMMXzJky4qDzpQT-JZcEUyn1xdHQTzfPQ
INFO - 2024-12-15 19:14:30,252  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA3MCwiaWF0IjoxNzM0MjgyODcwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.wnYOrgjUC3uMMXzJky4qDzpQT-JZcEUyn1xdHQTzfPQ'} 
INFO - 2024-12-15 19:14:30,253  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:14:30,261  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:14:30,268  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 19:14:39,450  -worker.py - Starting worker...
INFO - 2024-12-15 19:14:39,461  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:14:39,468  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 19:14:39,468  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA3MCwiaWF0IjoxNzM0MjgyODcwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.wnYOrgjUC3uMMXzJky4qDzpQT-JZcEUyn1xdHQTzfPQ'}
INFO - 2024-12-15 19:14:39,468  -worker.py - Processing reset password message
ERROR - 2024-12-15 19:14:39,473  -worker.py - Failed to process message: Exception raised The start_tls and use_tls options are not compatible., check your credentials or email service configuration
INFO - 2024-12-15 19:14:41,962  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:14:41,962  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:14:41,962  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA4MSwiaWF0IjoxNzM0MjgyODgxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.6eKQ_YrsYGFempL1JYV3o8wmaqRMt6C-yXdDgljBXTw
INFO - 2024-12-15 19:14:41,970  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA4MSwiaWF0IjoxNzM0MjgyODgxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.6eKQ_YrsYGFempL1JYV3o8wmaqRMt6C-yXdDgljBXTw'} 
INFO - 2024-12-15 19:14:41,970  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:14:41,978  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:14:41,986  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 19:14:41,986  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjA4MSwiaWF0IjoxNzM0MjgyODgxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.6eKQ_YrsYGFempL1JYV3o8wmaqRMt6C-yXdDgljBXTw'}
INFO - 2024-12-15 19:14:41,987  -worker.py - Processing reset password message
ERROR - 2024-12-15 19:14:41,992  -worker.py - Failed to process message: Exception raised The start_tls and use_tls options are not compatible., check your credentials or email service configuration
INFO - 2024-12-15 19:15:47,387  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:15:47,390  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:15:47,390  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE0NywiaWF0IjoxNzM0MjgyOTQ3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.UQ8TRL1SuIpmbX9L2DC56Ccfvp8DONz8Dh3dSV8P9Zo
INFO - 2024-12-15 19:15:47,400  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE0NywiaWF0IjoxNzM0MjgyOTQ3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.UQ8TRL1SuIpmbX9L2DC56Ccfvp8DONz8Dh3dSV8P9Zo'} 
INFO - 2024-12-15 19:15:47,400  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:15:47,404  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:15:47,408  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE0NywiaWF0IjoxNzM0MjgyOTQ3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.UQ8TRL1SuIpmbX9L2DC56Ccfvp8DONz8Dh3dSV8P9Zo'}
INFO - 2024-12-15 19:15:47,409  -worker.py - Processing reset password message
INFO - 2024-12-15 19:15:47,409  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
ERROR - 2024-12-15 19:15:47,414  -worker.py - Failed to process message: Exception raised The start_tls and use_tls options are not compatible., check your credentials or email service configuration
INFO - 2024-12-15 19:15:55,304  -worker.py - Starting worker...
INFO - 2024-12-15 19:15:55,315  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:15:55,321  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 19:15:57,379  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:15:57,379  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:15:57,379  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE1NywiaWF0IjoxNzM0MjgyOTU3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WjGXIgzFw2_dOYAVv9XW2GduFLMO0PB7tjkNsMvKRyU
INFO - 2024-12-15 19:15:57,384  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE1NywiaWF0IjoxNzM0MjgyOTU3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WjGXIgzFw2_dOYAVv9XW2GduFLMO0PB7tjkNsMvKRyU'} 
INFO - 2024-12-15 19:15:57,384  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:15:57,390  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:15:57,395  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-15 19:15:57,395  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDMyNjE1NywiaWF0IjoxNzM0MjgyOTU3LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WjGXIgzFw2_dOYAVv9XW2GduFLMO0PB7tjkNsMvKRyU'}
INFO - 2024-12-15 19:15:57,395  -worker.py - Processing reset password message
ERROR - 2024-12-15 19:15:58,604  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 19:20:29,577  -email_service.py - token type email_token
INFO - 2024-12-15 19:20:29,590  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NDI5LCJpYXQiOjE3MzQyODMyMjksInNjb3BlIjoiZW1haWxfdG9rZW4ifQ.Dg5CoNbTFv2NLRxYOg-equ430dK7cSW_u3BIQLS4ge8'} 
INFO - 2024-12-15 19:20:29,590  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:20:29,599  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:20:29,605  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email
INFO - 2024-12-15 19:20:29,606  -worker.py - Message data parsed: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NDI5LCJpYXQiOjE3MzQyODMyMjksInNjb3BlIjoiZW1haWxfdG9rZW4ifQ.Dg5CoNbTFv2NLRxYOg-equ430dK7cSW_u3BIQLS4ge8'}
INFO - 2024-12-15 19:20:29,607  -worker.py - Processing confirm email message
INFO - 2024-12-15 19:20:30,475  -worker.py - Message precessed successfully : dimacheban23@gmail.com. Type: confirm_email
INFO - 2024-12-15 19:20:54,782  -worker.py - Starting worker...
INFO - 2024-12-15 19:20:54,795  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:20:54,802  -worker.py - Worker is consuming messages...
INFO - 2024-12-15 19:21:22,554  -email_service.py - token type email_token
INFO - 2024-12-15 19:21:22,558  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NDgyLCJpYXQiOjE3MzQyODMyODIsInNjb3BlIjoiZW1haWxfdG9rZW4ifQ.JZKT_TG0W9l0IDVF59Uv-Xn6IUATO2LxvU60UYSM21Y'} 
INFO - 2024-12-15 19:21:22,558  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:21:22,566  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:21:22,573  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email
INFO - 2024-12-15 19:21:22,574  -worker.py - Message data parsed: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NDgyLCJpYXQiOjE3MzQyODMyODIsInNjb3BlIjoiZW1haWxfdG9rZW4ifQ.JZKT_TG0W9l0IDVF59Uv-Xn6IUATO2LxvU60UYSM21Y'}
INFO - 2024-12-15 19:21:22,574  -worker.py - Processing confirm email message
INFO - 2024-12-15 19:21:23,499  -worker.py - Message precessed successfully : dimacheban23@gmail.com. Type: confirm_email
INFO - 2024-12-15 19:21:57,273  -users.py - Get curent user finifsh test
INFO - 2024-12-15 19:21:57,278  -email_service.py - token type reset_password_token
INFO - 2024-12-15 19:21:57,278  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NTE3LCJpYXQiOjE3MzQyODMzMTcsInNjb3BlIjoicmVzZXRfcGFzc3dvcmRfdG9rZW4ifQ.-EYJ2n25ENV7msHKLUfgjX2bbxIr0geUA-vxh3qYh8o
INFO - 2024-12-15 19:21:57,288  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NTE3LCJpYXQiOjE3MzQyODMzMTcsInNjb3BlIjoicmVzZXRfcGFzc3dvcmRfdG9rZW4ifQ.-EYJ2n25ENV7msHKLUfgjX2bbxIr0geUA-vxh3qYh8o'} 
INFO - 2024-12-15 19:21:57,288  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-15 19:21:57,301  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-15 19:21:57,307  -worker.py - Message data parsed: {'email': 'dimacheban23@gmail.com', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAZ21haWwuY29tIiwiZXhwIjoxNzM0MzI2NTE3LCJpYXQiOjE3MzQyODMzMTcsInNjb3BlIjoicmVzZXRfcGFzc3dvcmRfdG9rZW4ifQ.-EYJ2n25ENV7msHKLUfgjX2bbxIr0geUA-vxh3qYh8o'}
INFO - 2024-12-15 19:21:57,307  -worker.py - Processing reset password message
INFO - 2024-12-15 19:21:57,307  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
ERROR - 2024-12-15 19:21:58,155  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-15 21:06:48,080  -users.py - start change password
ERROR - 2024-12-15 21:06:48,081  -conection_postgres.py - Session rollback, exception: 'ConfirmPassword' object has no attribute 'token'
INFO - 2024-12-15 21:07:45,444  -users.py - start change password
INFO - 2024-12-15 21:07:45,448  -users.py - get user
INFO - 2024-12-15 21:07:45,500  -users.py - validate password
ERROR - 2024-12-15 21:07:45,500  -conection_postgres.py - Session rollback, exception: 400: [{'type': 'missing', 'loc': ('token',), 'msg': 'Field required', 'input': {'new_psw': '12121212'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}, {'type': 'missing', 'loc': ('new_password',), 'msg': 'Field required', 'input': {'new_psw': '12121212'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}]
INFO - 2024-12-15 21:09:14,016  -users.py - start change password
INFO - 2024-12-15 21:09:14,022  -users.py - get user
INFO - 2024-12-15 21:09:14,149  -users.py - validate password
ERROR - 2024-12-15 21:09:14,149  -conection_postgres.py - Session rollback, exception: 400: [{'type': 'missing', 'loc': ('token',), 'msg': 'Field required', 'input': {'new_psw': '12121212'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}, {'type': 'missing', 'loc': ('new_password',), 'msg': 'Field required', 'input': {'new_psw': '12121212'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}]
INFO - 2024-12-15 21:09:53,551  -users.py - start change password
INFO - 2024-12-15 21:09:53,554  -users.py - get user
INFO - 2024-12-15 21:09:53,594  -users.py - validate password
ERROR - 2024-12-15 21:09:53,594  -conection_postgres.py - Session rollback, exception: 400: [{'type': 'missing', 'loc': ('token',), 'msg': 'Field required', 'input': {'new_password': '12121212'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}]
INFO - 2024-12-15 21:10:18,089  -users.py - start change password
INFO - 2024-12-15 21:10:18,090  -users.py - get user
INFO - 2024-12-15 21:10:18,095  -users.py - validate password
ERROR - 2024-12-15 21:10:18,096  -conection_postgres.py - Session rollback, exception: 400: [{'type': 'missing', 'loc': ('token',), 'msg': 'Field required', 'input': {'new_password': '123123123'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}]
INFO - 2024-12-15 21:13:08,469  -users.py - start change password
INFO - 2024-12-15 21:13:08,470  -users.py - get user
INFO - 2024-12-15 21:13:08,474  -users.py - validate password
ERROR - 2024-12-15 21:13:08,474  -conection_postgres.py - Session rollback, exception: 400: [{'type': 'missing', 'loc': ('token',), 'msg': 'Field required', 'input': {'new_password': '123123123'}, 'url': 'https://errors.pydantic.dev/2.10/v/missing'}]
INFO - 2024-12-15 21:16:10,105  -users.py - start change password
INFO - 2024-12-15 21:16:10,107  -users.py - get user
INFO - 2024-12-15 21:16:10,149  -users.py - old_password == ? new_password 
INFO - 2024-12-15 21:16:10,210  -users.py - test reset password
INFO - 2024-12-15 21:16:10,220  -users.py - test del reset_password_token
INFO - 2024-12-16 01:11:28,827  -worker.py - Starting worker...
INFO - 2024-12-16 01:11:28,841  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:11:28,846  -worker.py - Worker is consuming messages...
INFO - 2024-12-16 01:11:59,165  -email_service.py - token type email_token
INFO - 2024-12-16 01:11:59,175  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0NzUxOSwiaWF0IjoxNzM0MzA0MzE5LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.F6pbTkypuZBmz4tmypNtVq7LtDXY5kUYnPOFHRvPWWM'} 
INFO - 2024-12-16 01:11:59,175  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:11:59,183  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:11:59,187  -produser.py - Message published to RabbitMQ with routing_key 'confirm_email
INFO - 2024-12-16 01:11:59,187  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'confirm_email', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0NzUxOSwiaWF0IjoxNzM0MzA0MzE5LCJzY29wZSI6ImVtYWlsX3Rva2VuIn0.F6pbTkypuZBmz4tmypNtVq7LtDXY5kUYnPOFHRvPWWM'}
INFO - 2024-12-16 01:11:59,187  -worker.py - Processing confirm email message
INFO - 2024-12-16 01:12:00,407  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: confirm_email
INFO - 2024-12-16 01:12:11,956  -users.py - test open verifivation email
INFO - 2024-12-16 01:13:39,595  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:13:39,596  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:13:39,596  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0NzYxOSwiaWF0IjoxNzM0MzA0NDE5LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.x3_L7ZZ7FUnA1soD5b0B7nyoibXIdUZm-EG1WTje3Cw
INFO - 2024-12-16 01:13:39,603  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0NzYxOSwiaWF0IjoxNzM0MzA0NDE5LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.x3_L7ZZ7FUnA1soD5b0B7nyoibXIdUZm-EG1WTje3Cw'} 
INFO - 2024-12-16 01:13:39,603  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:13:39,617  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:13:39,624  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:13:39,625  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0NzYxOSwiaWF0IjoxNzM0MzA0NDE5LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.x3_L7ZZ7FUnA1soD5b0B7nyoibXIdUZm-EG1WTje3Cw'}
INFO - 2024-12-16 01:13:39,626  -worker.py - Processing reset password message
ERROR - 2024-12-16 01:13:40,737  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-16 01:20:38,999  -worker.py - Starting worker...
INFO - 2024-12-16 01:20:39,012  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:20:39,017  -worker.py - Worker is consuming messages...
INFO - 2024-12-16 01:20:51,639  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:20:51,641  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:20:51,641  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODA1MSwiaWF0IjoxNzM0MzA0ODUxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.0XHJQDHQ16zpWBKKOsntFy4prYmkgfzBhjTEpWJF4RM
INFO - 2024-12-16 01:20:51,648  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODA1MSwiaWF0IjoxNzM0MzA0ODUxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.0XHJQDHQ16zpWBKKOsntFy4prYmkgfzBhjTEpWJF4RM'} 
INFO - 2024-12-16 01:20:51,649  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:20:51,656  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:20:51,661  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:20:51,661  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODA1MSwiaWF0IjoxNzM0MzA0ODUxLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.0XHJQDHQ16zpWBKKOsntFy4prYmkgfzBhjTEpWJF4RM'}
INFO - 2024-12-16 01:20:51,661  -worker.py - Processing reset password message
ERROR - 2024-12-16 01:20:52,911  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-16 01:23:58,869  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:23:58,870  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:23:58,870  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODIzOCwiaWF0IjoxNzM0MzA1MDM4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.HryNPyWWtgCsZ5tNmqPnnGl8ZLSEDeMP8Lz77p0_T4I
INFO - 2024-12-16 01:23:58,877  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODIzOCwiaWF0IjoxNzM0MzA1MDM4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.HryNPyWWtgCsZ5tNmqPnnGl8ZLSEDeMP8Lz77p0_T4I'} 
INFO - 2024-12-16 01:23:58,877  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:23:58,887  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:23:58,894  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:23:58,895  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODIzOCwiaWF0IjoxNzM0MzA1MDM4LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.HryNPyWWtgCsZ5tNmqPnnGl8ZLSEDeMP8Lz77p0_T4I'}
INFO - 2024-12-16 01:23:58,896  -worker.py - Processing reset password message
ERROR - 2024-12-16 01:24:00,114  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-16 01:24:05,653  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:24:05,654  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:24:05,654  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODI0NSwiaWF0IjoxNzM0MzA1MDQ1LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WWDQn4cuRO6OTbGlUSp50Vu4Y4J0eoZ-eB6LKIlULDE
INFO - 2024-12-16 01:24:05,662  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODI0NSwiaWF0IjoxNzM0MzA1MDQ1LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WWDQn4cuRO6OTbGlUSp50Vu4Y4J0eoZ-eB6LKIlULDE'} 
INFO - 2024-12-16 01:24:05,662  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:24:05,670  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:24:05,676  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:24:34,623  -worker.py - Starting worker...
INFO - 2024-12-16 01:24:34,636  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:24:34,643  -worker.py - Worker is consuming messages...
INFO - 2024-12-16 01:24:34,643  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODI0NSwiaWF0IjoxNzM0MzA1MDQ1LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.WWDQn4cuRO6OTbGlUSp50Vu4Y4J0eoZ-eB6LKIlULDE'}
INFO - 2024-12-16 01:24:34,643  -worker.py - Processing reset password message
ERROR - 2024-12-16 01:24:35,761  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-16 01:24:59,401  -worker.py - Starting worker...
INFO - 2024-12-16 01:24:59,411  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:24:59,417  -worker.py - Worker is consuming messages...
INFO - 2024-12-16 01:25:02,601  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:25:02,602  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:25:02,602  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODMwMiwiaWF0IjoxNzM0MzA1MTAyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.4NGERWby7ywySW08QvEALh80bk98avjoFPtjm4bit8g
INFO - 2024-12-16 01:25:02,608  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODMwMiwiaWF0IjoxNzM0MzA1MTAyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.4NGERWby7ywySW08QvEALh80bk98avjoFPtjm4bit8g'} 
INFO - 2024-12-16 01:25:02,608  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:25:02,615  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:25:02,622  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:25:02,622  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODMwMiwiaWF0IjoxNzM0MzA1MTAyLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.4NGERWby7ywySW08QvEALh80bk98avjoFPtjm4bit8g'}
INFO - 2024-12-16 01:25:02,622  -worker.py - Processing reset password message
ERROR - 2024-12-16 01:25:03,717  -worker.py - Failed to process message: (550, 'Message subject: SPAM FOUND')
INFO - 2024-12-16 01:27:20,105  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:27:20,109  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:27:20,109  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0MCwiaWF0IjoxNzM0MzA1MjQwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.CWMB-bjeCv5BAbO9sEAj60NyHDE7KwLvnpm1HwRKuAc
INFO - 2024-12-16 01:27:20,121  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0MCwiaWF0IjoxNzM0MzA1MjQwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.CWMB-bjeCv5BAbO9sEAj60NyHDE7KwLvnpm1HwRKuAc'} 
INFO - 2024-12-16 01:27:20,122  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:27:20,129  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:27:20,135  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:27:24,368  -worker.py - Starting worker...
INFO - 2024-12-16 01:27:24,378  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:27:24,384  -worker.py - Worker is consuming messages...
INFO - 2024-12-16 01:27:24,384  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0MCwiaWF0IjoxNzM0MzA1MjQwLCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.CWMB-bjeCv5BAbO9sEAj60NyHDE7KwLvnpm1HwRKuAc'}
INFO - 2024-12-16 01:27:24,384  -worker.py - Processing reset password message
INFO - 2024-12-16 01:27:25,643  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: reset_password
INFO - 2024-12-16 01:27:26,494  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:27:26,494  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:27:26,494  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0NiwiaWF0IjoxNzM0MzA1MjQ2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.l9A47wMPrDGKP1xIv2n3pGjqxFJmIYQQGc310O7upkU
INFO - 2024-12-16 01:27:26,499  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0NiwiaWF0IjoxNzM0MzA1MjQ2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.l9A47wMPrDGKP1xIv2n3pGjqxFJmIYQQGc310O7upkU'} 
INFO - 2024-12-16 01:27:26,499  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:27:26,504  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:27:26,509  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODQ0NiwiaWF0IjoxNzM0MzA1MjQ2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.l9A47wMPrDGKP1xIv2n3pGjqxFJmIYQQGc310O7upkU'}
INFO - 2024-12-16 01:27:26,509  -worker.py - Processing reset password message
INFO - 2024-12-16 01:27:26,509  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:27:27,717  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: reset_password
INFO - 2024-12-16 01:30:06,140  -users.py - Get curent user finifsh test
INFO - 2024-12-16 01:30:06,141  -email_service.py - token type reset_password_token
INFO - 2024-12-16 01:30:06,141  -users.py - toke = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODYwNiwiaWF0IjoxNzM0MzA1NDA2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.fy9yIIPkPoNAeuKGtYhvSWoRuX0U0XeXfyeXjo40BVA
INFO - 2024-12-16 01:30:06,147  -email_service.py - Sending email task to RabbitMQ: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODYwNiwiaWF0IjoxNzM0MzA1NDA2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.fy9yIIPkPoNAeuKGtYhvSWoRuX0U0XeXfyeXjo40BVA'} 
INFO - 2024-12-16 01:30:06,147  -produser.py - Preparing to send message to RabbitMQ
INFO - 2024-12-16 01:30:06,159  -connection_rabbit.py - rabbitmq conn TRUE
INFO - 2024-12-16 01:30:06,167  -produser.py - Message published to RabbitMQ with routing_key 'reset_password
INFO - 2024-12-16 01:30:06,168  -worker.py - Message data parsed: {'email': 'dimacheban23@meta.ua', 'username': 'test', 'host': 'http://127.0.0.1:8000/', 'queue_name': 'reset_password', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaW1hY2hlYmFuMjNAbWV0YS51YSIsImV4cCI6MTczNDM0ODYwNiwiaWF0IjoxNzM0MzA1NDA2LCJzY29wZSI6InJlc2V0X3Bhc3N3b3JkX3Rva2VuIn0.fy9yIIPkPoNAeuKGtYhvSWoRuX0U0XeXfyeXjo40BVA'}
INFO - 2024-12-16 01:30:06,168  -worker.py - Processing reset password message
INFO - 2024-12-16 01:30:07,366  -worker.py - Message precessed successfully : dimacheban23@meta.ua. Type: reset_password
INFO - 2024-12-16 01:30:39,444  -users.py - start change password
INFO - 2024-12-16 01:30:39,446  -users.py - get user
INFO - 2024-12-16 01:30:39,449  -users.py - old_password == ? new_password 
INFO - 2024-12-16 01:30:39,523  -users.py - test reset password
INFO - 2024-12-16 01:30:39,527  -users.py - test del reset_password_token
INFO - 2024-12-16 01:30:52,191  -users.py - start change password
INFO - 2024-12-16 01:30:52,191  -users.py - get user
INFO - 2024-12-16 01:30:52,196  -users.py - old_password == ? new_password 
WARNING - 2024-12-16 01:30:52,204  -users.py - new password == old password, test, 123123
ERROR - 2024-12-16 01:30:52,205  -conection_postgres.py - Session rollback, exception: 400: New password is the same as old password
